name: canary
on:
  push:
    branches:
      - canary 
  workflow_run:
    workflows: 
      - main
    types:
      - completed
jobs:  
  pre_cond: 
    name: Precondition to run CI
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success') || github.ref == 'refs/heads/canary'}}
    steps:
    - name: Print trigger info
      run: |       
        echo "triggering branch - ${{ github.ref }}"        
        echo "triggering ci result - ${{ github.event.workflow_run.conclusion }}" 
  build:
    name: Build after checkout & merge
    runs-on: ubuntu-latest
    needs: pre_cond
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 10
        ref: main
    - name: Checkout Canary and Merge Master to it
      run: |       
        git config user.name github-actions
        git config user.email github-actions@github.com   
        git fetch    
        git checkout canary 
        git merge main
        git commit -m "automerging main to canary" || echo "Nothing to commit"
        git push
    - name: Build
      run: echo 'Building... blah blah...'
    - name: Deploy
      run: echo 'Deploying... blah blah...'