name: main
on:
  push:
    branches:
      - main
jobs:  
  build:
    name: Build after checkout 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Build
      run: echo 'Building... blah blah...'
      shell: bash      
    - name: Deploy
      run: echo 'Deploying... blah blah...'
      shell: bash