name: main
on:
  push:
    branches:
      - main
jobs:  
  build:
    name: Build after checkout 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
    - name: Build
      run: echo 'Building... blah blah...'
      shell: bash      
    - name: Deploy
      run: echo 'Deploying... blah blah...'
      shell: bash
  fail_step:
    name: Failing step 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Canary and Merge Master to it
      run: |       
        git config user.name github-actions
        git config user.email github-actions@github.com   
        git commit -m "automerging main to canary"